version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:2.3.2
    ports:
      - 4566:4566
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - DOCKER_SOCK=/var/run/docker.sock
      - DEBUG=1
    volumes:
      - localstack:/var/lib/localstack/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./local_script:/etc/localstack/init/ready.d
    networks:
      localstack-network:

networks:
  localstack-network:
volumes:
  localstack:
